service: zoom-recording-lambda

provider:
  name: aws
  runtime: nodejs21.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    GITHUB_REPO: ${env:GITHUB_REPO}

functions:
  processRecording:
    handler: index.handler
    events:
      - http:
          path: webhook
          method: post

plugins:
  - serverless-offline
