service: zoom-recording-lambda

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  processRecording:
    handler: index.handler
    events:
      - http:
          path: webhook
          method: post

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
custom:
  dotenv:
    path: ./.env
